name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - run: npm ci
      working-directory: client

    - run: npm run build
      working-directory: client
      env:
        CI: false

    - name: Verify build folder exists
      run: ls -alh client/build

    - name: Upload build folder
      uses: actions/upload-artifact@v3
      with:
        name: build-folder
        path: client/build

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
      with:
        # GitHub token
        token: ${{ github.token }}
        # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
        timeout: 600000
        # Maximum number of status report errors before cancelling a deployment (default: 10)
        error_count: 10
        # Time in milliseconds between two deployment status report (default: 5 seconds)
        reporting_interval: 5000
        # Name of the artifact to deploy
        artifact_name: build-folder
        # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
        preview: false
              
